clc;
dx=0.001; %as per case
NX=1+1/dx;
%% Compare density solution
a1 = matfile('UFDS_density.mat');
d1=a1.d;
a2 = matfile('RKwAD_density.mat');
d2=a2.d;
a3 = matfile('GwMUSCL_density.mat');
d3=a3.d;
a4 = matfile('GwENO_density.mat');
d4=a4.d;
x=linspace(0,1,NX);
figure;
plot(x,d1,"magenta",x,d2,"-.black",x,d3,"--red",x,d4,":blue");
xlabel('Location (x)');
ylabel('Density (\rho)');
ylim([0 1.5]);
title('Density (case 2)');
% legend('Upwind-Flux difference splitting','R-K w/ artificial dissipation','Godunov w/ MUSCL scheme','Godunov w/ ENO scheme','Location','northwest');
set(gca,'XMinorTick','on','YMinorTick','on','TickLength',[0.02,0.005]);
grid on;
%% Compare velocity solution
b1 = matfile('UFDS_velocity.mat');
v1=b1.v;
b2 = matfile('RKwAD_velocity.mat');
v2=b2.v;
b3 = matfile('GwMUSCL_velocity.mat');
v3=b3.v;
b4 = matfile('GwENO_velocity.mat');
v4=b4.v;
x=linspace(0,1,NX);
figure;
plot(x,v1,"magenta",x,v2,"-.black",x,v3,"--red",x,v4,":blue");
xlabel('Location (x)');
ylabel('Velocity (u)');
ylim([0 2]);
title('Velocity (case 2)');
% legend('Upwind-Flux difference splitting','R-K w/ artificial dissipation','Godunov w/ MUSCL scheme','Godunov w/ ENO scheme','Location','northwest');
set(gca,'XMinorTick','on','YMinorTick','on','TickLength',[0.02,0.005]);
grid on;
%% Compare pressure solution
c1 = matfile('UFDS_pressure.mat');
p1=c1.P;
c2 = matfile('RKwAD_pressure.mat');
p2=c2.P;
c3 = matfile('GwMUSCL_pressure.mat');
p3=c3.P;
c4 = matfile('GwENO_pressure.mat');
p4=c4.P;
x=linspace(0,1,NX);
figure;
plot(x,p1,"magenta",x,p2,"-.black",x,p3,"--red",x,p3,":blue");
xlabel('Location (x)');
ylabel('Pressure (P)');
ylim([0 5]);
title('Pressure (case 2)');
legend('Upwind-Flux difference splitting','R-K w/ artificial dissipation','Godunov w/ MUSCL scheme','Godunov w/ ENO scheme','Location','north');
set(gca,'XMinorTick','on','YMinorTick','on','TickLength',[0.02,0.005]);
grid on;
%% Compare internal energy solution
f1 = matfile('UFDS_energy.mat');
e1=f1.U;
f2 = matfile('RKwAD_energy.mat');
e2=f2.U;
f3 = matfile('GwMUSCL_energy.mat');
e3=f3.U;
f4 = matfile('GwENO_energy.mat');
e4=f4.U;
x=linspace(0,1,NX);
figure;
plot(x,e1,"magenta",x,e2,"-.black",x,e3,"--red",x,e4,":blue");
xlabel('Location (x)');
ylabel('Internal Energy (e)');
ylim([0 25]);
title('Internal energy (case 2)');
% legend('Upwind-Flux difference splitting','R-K w/ artificial dissipation','Godunov w/ MUSCL scheme','Godunov w/ ENO scheme','Location','northwest');
set(gca,'XMinorTick','on','YMinorTick','on','TickLength',[0.02,0.005]);
grid on;