clc;
figure;
x=linspace(-pi,pi);
y=linspace(-pi/2,pi/2);
[X,Y]=meshgrid(x,y);
P=-(cos(X.*2)+cos(Y.*2))/4;
contourf(X,Y,P);
clim([-0.5 0.4]);
colorbar;
title('Pressure contours using analytical solution ');
xlabel('X (m)');
ylabel('Y (m)');
axis([-pi pi -pi/2 pi/2]);
set(gca,'XTick',-pi:pi/4:pi); 
set(gca,'XTickLabel',{'-\pi','-3\pi/4','-\pi/2','-\pi/4','0','\pi/4','\pi/2','3\pi/4','\pi'});
set(gca,'YTick',-pi/2:pi/4:pi/2); 
set(gca,'YTickLabel',{'-\pi/2','-\pi/4','0','\pi/4','\pi/2'});
a=colorbar;
a.Label.String = 'Pressure (Pa)';
set(gca,'XMinorTick','on','YMinorTick','on','TickLength',[0.02,0.005]);